/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FOkCS4Lv6Uh
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:


To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export default function ProblemStructure() {
  return (
    <div className="bg-background text-foreground p-6 md:p-8 lg:p-12 rounded-lg shadow-lg">
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold">Competitive Programming Problem</h1>
          <p className="text-muted-foreground">A challenging problem for coding enthusiasts.</p>
        </div>
        <div>
          <h2 className="text-2xl font-semibold">Problem Statement</h2>
          <p>
            Given an array of integers, find the maximum sum of non-adjacent elements. In other words, you need to pick
            a set of non-overlapping elements from the array such that the sum of their values is maximized.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-semibold">Input</h2>
          <p>
            The first line of input contains an integer <code>n</code> representing the length of the array. The second
            line contains <code>n</code> space-separated integers representing the elements of the array.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-semibold">Output</h2>
          <p>Return the maximum sum of non-adjacent elements.</p>
        </div>
        <div>
          <h2 className="text-2xl font-semibold">Example</h2>
          <div className="bg-muted p-4 rounded-md">
            <h3 className="text-lg font-semibold">Example 1</h3>
            <p>
              <strong>Input:</strong> <code>[2, 4, 1, 5, 3]</code>
            </p>
            <p>
              <strong>Output:</strong> <code>9</code>
            </p>
            <p>
              The maximum sum of non-adjacent elements is <code>4 + 5 = 9</code>.
            </p>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold">Test Cases</h2>
          <div className="flex flex-col gap-2">
            <button className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
              Download Test Cases
            </button>
            <p className="text-muted-foreground">
              The test cases are available in a .txt file for you to download and use.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
