import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

const libre = Libre_Franklin({
  subsets: ['latin'],
  display: 'swap',
})

const rubi = Rubik({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${libre.className} ${rubi.className}`}>{children}</body>
    </html>
  );
}
